version: "3"
services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql_sandbox
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --secure-file-priv=""
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: test_database
      LANG: ja_JP.UTF-8
    ports:
      - 63306:3306
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

